"""empty message

Revision ID: 5059a2aa7375
Revises: 
Create Date: 2018-08-02 10:44:31.973847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5059a2aa7375'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_kpi_report', sa.Column('total_inc_amt', sa.Float(), nullable=True))
    op.drop_column('daily_kpi_report', 'total_consume_amt')
    op.drop_column('daily_kpi_report', 'live_and_video_gift_arpu')
    op.drop_column('daily_kpi_report', 'total_consume_uids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_kpi_report', sa.Column('total_consume_uids', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('daily_kpi_report', sa.Column('live_and_video_gift_arpu', mysql.FLOAT(), nullable=True))
    op.add_column('daily_kpi_report', sa.Column('total_consume_amt', mysql.FLOAT(), nullable=True))
    op.drop_column('daily_kpi_report', 'total_inc_amt')
    # ### end Alembic commands ###
